name: Build and Deploy Vue to Docker

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 使用最新版本

    - name: Build Docker image
      run: |
        docker build -t suansuanru9999/net-search:latest .  # 使用根目录的 Dockerfile

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push suansuanru9999/net-search:latest
