name: Build and Deploy Vue to Docker

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # 或者你需要的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Build Docker image
      run: |
        docker build -t your-docker-image-name:latest .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: docker push suansuanru9999/net-search:latest
